export const useTypes = () => {

    return {
        FETCH_USER_START: "FETCH_USER_START",
        FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
        FETCH_USER_FAILED: "FETCH_USER_FAILED",
        FETCH_USER_STOP: "FETCH_USER_STOP",
        LOGIN_START: "LOGIN_START",
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        LOGIN_FAILED: "LOGIN_FAILED",
        LOGIN_STOP: "LOGIN_STOP"
    }
}

